name: oxy_http
description: A starting point for Dart libraries or applications.
version: 0.0.1
repository: https://github.com/medz/oxy
homepage: https://github.com/medz/oxy/tree/main/pub/oxy_http

topics:
  - http
  - fetch
  - web
  - request
  - response

funding:
  - https://github.com/sponsors/medz
  - https://opencollective.com/openodroe

resolution: workspace
environment:
  sdk: ^3.8.1

dependencies:
  oxy: ^0.0.1
  http: ^1.4.0
dev_dependencies:
  freeport: ^0.0.2
