name: oxy_http
description: A HTTP adapter for Oxy that uses Dart's http package as the underlying HTTP implementation.
version: 0.0.1
repository: https://github.com/medz/oxy
homepage: https://github.com/medz/oxy/tree/main/pub/oxy_http

topics:
  - http
  - fetch
  - web
  - request
  - response

funding:
  - https://github.com/sponsors/medz
  - https://opencollective.com/openodroe

resolution: workspace
environment:
  sdk: ^3.8.1

dependencies:
  oxy: ^0.0.3
  http: ^1.4.0
